codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default: false  # disable the default status that measures entire project
        tests:  # declare a new status context "tests"
          target: 100%  # we always want 100% coverage here
          paths: "tests/"  # only include coverage in "tests/" folder
        jupyter:  # declare a new status context "app"
          paths: "!tests/"  # remove all files in "tests/"
          
        if_ci_failed: error #success, failure, error, ignore
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  
